### ISSUE TITLE
Lowercase Headers

### ISSUE THREAD

**Issue by BDDCloud** [bbyars/mountebank#75]
I'm using the recording capability, and what I found is that it seems HTTP headers as upper case going through the proxy are reaching the destination as lower case.

There's a silly constraint on a web service that a certain incoming header must be all uppercase, so the recording is blocked by the lower case header.

**Comment by bbyars** [comment]
Yep, seems like that should be fixed.  I'll get to this soon.  Thanks for
reporting.
-Brandon

**Comment by bbyars** [comment]
Fixed with 4f56ae4; will get a new release out soon, but in the meantime you can use one of the pre-release packages on http://mountebank-dev.herokuapp.com/docs/install (or npm install mountebank-test)

**Comment by bbyars** [comment]
Released with v1.4.1 today: http://www.mbtest.org/

**Comment by sunfreakz** [comment]
I'm still experiencing this problem with 1.4.2 :(
Mountebank is set to proxy requests.
```
root@77430c6803c6:/# curl -i http://keystone/arara/ururu
HTTP/1.1 401 Unauthorized
Server: nginx/1.8.0
Date: Mon, 11 Jan 2016 11:54:13 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive

{"status":401,"msg":"Unauthorized"}
```
```
root@77430c6803c6:/# curl -i http://localhost:4545/arara/ururu               
HTTP/1.1 401 Unauthorized
server: nginx/1.8.0
date: Mon, 11 Jan 2016 11:48:36 GMT
content-type: application/json
transfer-encoding: chunked
connection: close

{"status":401,"msg":"Unauthorized"}
```

**Comment by bbyars** [comment]
Thanks Andrew.  The previous fix addressed maintaining case sensitivity for
the headers reaching the origin server.  I just committed a fix for
maintaining the case on the way back and will release it soon.
-Brandon

**Comment by bbyars** [comment]
Just released v1.4.3; this should be fixed now.
